name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Warcraft"
  comment: "Warcraft"
  url: "https://download131.uploadhaven.com/1/application/zip/LIvgYPSIY38q0yhCxWCGQMIpqDrBh6OHONzLt3UB.zip?key=Na0BbNiFzIuUy3XfdGgrsw&expire=1697904686&filename=Warcraft.III.Reforged.Spoils.of.War.zip"
  file_name: "Warcraft"
  piece_size: 24 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
